text/* bat --paging=never --color=always %pistol-filename%
text/html w3m -T text/html -dump %pistol-filename%
inode/directory ls -l --color %pistol-filename%

fpath /var/src/my-bash-project/bin/[^/]+$ bat --map-syntax :bash --paging=never --color=always %pistol-filename%

application/json sh: jq '.' %pistol-filename%

fpath .*.md$ sh: bat --paging=never --color=always %pistol-filename% | head -8

fpath /problematic-bz2/.*.bz2 bzip2 %pistol-filename% %pistol-extra0%
fpath /working-bz2/.*.bz2     bzip2 %pistol-filename%

image/.* pv %pistol-filename% %pistol-extra0% %pistol-extra1% %pistol-extra2% %pistol-extra3%
