mute=yes
keep-open
cache=yes
cache-on-disk=no

profile=gpu-hq
# scale=ewa_lanczossharp
# cscale=ewa_lanczossharp
# video-sync=display-resample
# interpolation
tscale=oversample

volume-max=200
volume=80
